version: '3'

services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    networks:
      - prod-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker-test
      
  appserver:
    build:
      dockerfile: ./src/main/docker/Dockerfile
      context: .
    image: brunosc/docker-spring-boot-test:mysql
    container_name: appserver-docker-test-1
    ports:
      - "8080:8080"
    networks: 
      - prod-network
    depends_on:
      - "mysql"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=docker-test
      - DATABASE_PORT=3306
      - SPRING_PROFILES_ACTIVE=container
      - DEBUG=true
      
networks: 
  prod-network:
    driver: bridge      